create table if not exists public.bet_board_state (
  id text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.bet_boards (
  id text primary key,
  active_match_id text,
  app_version integer not null default 11,
  updated_at timestamptz not null default now()
);

create table if not exists public.bet_matches (
  id text primary key,
  board_id text not null references public.bet_boards(id) on delete cascade,
  title text not null,
  match_date text not null,
  dinner_price integer not null default 0,
  settlement_mode text not null default 'share-ratio',
  fund_rule jsonb not null default '{"roundAmount":10000,"rankAllocations":[2000,3000,5000]}'::jsonb,
  my_participant_id text,
  match_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.bet_participants (
  match_id text not null references public.bet_matches(id) on delete cascade,
  id text not null,
  name text not null,
  initial_handicap integer not null default 0,
  participant_order integer not null default 0,
  primary key (match_id, id)
);

create table if not exists public.bet_rounds (
  id bigint generated by default as identity primary key,
  match_id text not null references public.bet_matches(id) on delete cascade,
  round_no integer not null,
  rule text not null default 'field-average',
  is_draw boolean not null default false,
  winner_id text,
  loser_id text,
  course_name text,
  holes_played integer not null default 18,
  completion_status text not null default 'completed',
  partial_round_policy text,
  fund_rule jsonb,
  round_order integer not null default 0,
  unique (match_id, round_no)
);

create table if not exists public.bet_round_scores (
  match_id text not null,
  round_no integer not null,
  participant_id text not null,
  strokes integer not null,
  score_order integer not null default 0,
  primary key (match_id, round_no, participant_id),
  foreign key (match_id, round_no) references public.bet_rounds(match_id, round_no) on delete cascade,
  foreign key (match_id, participant_id) references public.bet_participants(match_id, id) on delete cascade
);

create index if not exists bet_matches_board_order_idx
on public.bet_matches(board_id, match_order);

create index if not exists bet_participants_match_order_idx
on public.bet_participants(match_id, participant_order);

create index if not exists bet_rounds_match_order_idx
on public.bet_rounds(match_id, round_order);

create index if not exists bet_round_scores_round_order_idx
on public.bet_round_scores(match_id, round_no, score_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_bet_board_state_updated_at on public.bet_board_state;
create trigger set_bet_board_state_updated_at
before update on public.bet_board_state
for each row
execute function public.set_updated_at();

drop trigger if exists set_bet_boards_updated_at on public.bet_boards;
create trigger set_bet_boards_updated_at
before update on public.bet_boards
for each row
execute function public.set_updated_at();

drop trigger if exists set_bet_matches_updated_at on public.bet_matches;
create trigger set_bet_matches_updated_at
before update on public.bet_matches
for each row
execute function public.set_updated_at();

alter table public.bet_board_state enable row level security;
alter table public.bet_boards enable row level security;
alter table public.bet_matches enable row level security;
alter table public.bet_participants enable row level security;
alter table public.bet_rounds enable row level security;
alter table public.bet_round_scores enable row level security;

drop policy if exists "Anyone can read bet board state" on public.bet_board_state;
drop policy if exists "Anyone can create bet board state" on public.bet_board_state;
drop policy if exists "Anyone can update bet board state" on public.bet_board_state;
drop policy if exists "Anyone can manage bet board state" on public.bet_board_state;
drop policy if exists "Anyone can manage bet boards" on public.bet_boards;
drop policy if exists "Anyone can manage bet matches" on public.bet_matches;
drop policy if exists "Anyone can manage bet participants" on public.bet_participants;
drop policy if exists "Anyone can manage bet rounds" on public.bet_rounds;
drop policy if exists "Anyone can manage bet round scores" on public.bet_round_scores;

create policy "Anyone can manage bet board state"
on public.bet_board_state
for all
to anon
using (true)
with check (true);

create policy "Anyone can manage bet boards"
on public.bet_boards
for all
to anon
using (true)
with check (true);

create policy "Anyone can manage bet matches"
on public.bet_matches
for all
to anon
using (true)
with check (true);

create policy "Anyone can manage bet participants"
on public.bet_participants
for all
to anon
using (true)
with check (true);

create policy "Anyone can manage bet rounds"
on public.bet_rounds
for all
to anon
using (true)
with check (true);

create policy "Anyone can manage bet round scores"
on public.bet_round_scores
for all
to anon
using (true)
with check (true);

create or replace function public.save_bet_board_state(
  p_board_id text,
  p_state jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match record;
  v_participant record;
  v_round record;
  v_score record;
  v_match_id text;
  v_round_no integer;
begin
  insert into public.bet_boards (id, active_match_id, app_version, updated_at)
  values (
    p_board_id,
    p_state->>'activeMatchId',
    coalesce((p_state->>'version')::integer, 11),
    now()
  )
  on conflict (id) do update
  set
    active_match_id = excluded.active_match_id,
    app_version = excluded.app_version,
    updated_at = now();

  delete from public.bet_matches
  where board_id = p_board_id;

  for v_match in
    select value as data, ordinality::integer as sort_order
    from jsonb_array_elements(coalesce(p_state->'matches', '[]'::jsonb)) with ordinality
  loop
    v_match_id := v_match.data->>'id';

    insert into public.bet_matches (
      id,
      board_id,
      title,
      match_date,
      dinner_price,
      settlement_mode,
      fund_rule,
      my_participant_id,
      match_order,
      updated_at
    )
    values (
      v_match_id,
      p_board_id,
      coalesce(v_match.data->>'title', '오늘 내기'),
      coalesce(v_match.data->>'date', ''),
      coalesce((v_match.data->>'dinnerPrice')::integer, 0),
      coalesce(v_match.data->>'settlementMode', 'share-ratio'),
      coalesce(v_match.data->'fundRule', '{"roundAmount":10000,"rankAllocations":[2000,3000,5000]}'::jsonb),
      v_match.data->>'myParticipantId',
      v_match.sort_order,
      coalesce((v_match.data->>'updatedAt')::timestamptz, now())
    );

    for v_participant in
      select value as data, ordinality::integer as sort_order
      from jsonb_array_elements(coalesce(v_match.data->'participants', '[]'::jsonb)) with ordinality
    loop
      insert into public.bet_participants (
        match_id,
        id,
        name,
        initial_handicap,
        participant_order
      )
      values (
        v_match_id,
        v_participant.data->>'id',
        coalesce(v_participant.data->>'name', '참가자'),
        coalesce((v_participant.data->>'initialHandicap')::integer, 0),
        v_participant.sort_order
      );
    end loop;

    for v_round in
      select value as data, ordinality::integer as sort_order
      from jsonb_array_elements(coalesce(v_match.data->'history', '[]'::jsonb)) with ordinality
    loop
      v_round_no := coalesce((v_round.data->>'round')::integer, v_round.sort_order);

      insert into public.bet_rounds (
        match_id,
        round_no,
        rule,
        is_draw,
        winner_id,
        loser_id,
        course_name,
        holes_played,
        completion_status,
        partial_round_policy,
        fund_rule,
        round_order
      )
      values (
        v_match_id,
        v_round_no,
        coalesce(v_round.data->>'rule', 'field-average'),
        coalesce((v_round.data->>'isDraw')::boolean, false),
        v_round.data->>'winnerId',
        v_round.data->>'loserId',
        nullif(v_round.data->>'courseName', ''),
        coalesce((v_round.data->>'holesPlayed')::integer, 18),
        coalesce(v_round.data->>'completionStatus', 'completed'),
        v_round.data->>'partialRoundPolicy',
        v_round.data->'fundRule',
        v_round.sort_order
      );

      for v_score in
        select value as data, ordinality::integer as sort_order
        from jsonb_array_elements(coalesce(v_round.data->'scores', '[]'::jsonb)) with ordinality
      loop
        insert into public.bet_round_scores (
          match_id,
          round_no,
          participant_id,
          strokes,
          score_order
        )
        values (
          v_match_id,
          v_round_no,
          v_score.data->>'participantId',
          coalesce((v_score.data->>'strokes')::integer, 0),
          v_score.sort_order
        );
      end loop;
    end loop;
  end loop;

  insert into public.bet_board_state (id, state, updated_at)
  values (p_board_id, p_state, now())
  on conflict (id) do update
  set
    state = excluded.state,
    updated_at = now();
end;
$$;

create or replace function public.get_bet_board_state(p_board_id text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case
    when b.id is null then null
    else jsonb_build_object(
      'version', b.app_version,
      'activeMatchId', b.active_match_id,
      'matches', coalesce(
        (
          select jsonb_agg(
            jsonb_strip_nulls(
              jsonb_build_object(
                'id', m.id,
                'title', m.title,
                'date', m.match_date,
                'dinnerPrice', m.dinner_price,
                'settlementMode', m.settlement_mode,
                'fundRule', m.fund_rule,
                'myParticipantId', m.my_participant_id,
                'participants', coalesce(
                  (
                    select jsonb_agg(
                      jsonb_build_object(
                        'id', p.id,
                        'name', p.name,
                        'initialHandicap', p.initial_handicap
                      )
                      order by p.participant_order
                    )
                    from public.bet_participants p
                    where p.match_id = m.id
                  ),
                  '[]'::jsonb
                ),
                'history', coalesce(
                  (
                    select jsonb_agg(
                      jsonb_strip_nulls(
                        jsonb_build_object(
                          'round', r.round_no,
                          'scores', coalesce(
                            (
                              select jsonb_agg(
                                jsonb_build_object(
                                  'participantId', s.participant_id,
                                  'strokes', s.strokes
                                )
                                order by s.score_order
                              )
                              from public.bet_round_scores s
                              where s.match_id = r.match_id
                                and s.round_no = r.round_no
                            ),
                            '[]'::jsonb
                          ),
                          'isDraw', r.is_draw,
                          'loserId', r.loser_id,
                          'rule', r.rule,
                          'winnerId', r.winner_id,
                          'courseName', r.course_name,
                          'holesPlayed', r.holes_played,
                          'completionStatus', r.completion_status,
                          'partialRoundPolicy', r.partial_round_policy,
                          'fundRule', r.fund_rule
                        )
                      )
                      order by r.round_order
                    )
                    from public.bet_rounds r
                    where r.match_id = m.id
                  ),
                  '[]'::jsonb
                ),
                'updatedAt', to_char(m.updated_at at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
              )
            )
            order by m.match_order
          )
          from public.bet_matches m
          where m.board_id = b.id
        ),
        '[]'::jsonb
      )
    )
  end
  from public.bet_boards b
  where b.id = p_board_id;
$$;

create or replace function public.migrate_bet_board_state_to_relational()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_record record;
  v_count integer := 0;
begin
  for v_record in
    select id, state
    from public.bet_board_state
  loop
    perform public.save_bet_board_state(v_record.id, v_record.state);
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

revoke all on function public.get_bet_board_state(text) from public;
revoke all on function public.save_bet_board_state(text, jsonb) from public;
revoke all on function public.migrate_bet_board_state_to_relational() from public;

grant execute on function public.get_bet_board_state(text) to anon;
grant execute on function public.save_bet_board_state(text, jsonb) to anon;

do $$
declare
  v_table text;
begin
  if not exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    create publication supabase_realtime;
  end if;

  foreach v_table in array array[
    'bet_board_state',
    'bet_boards',
    'bet_matches',
    'bet_participants',
    'bet_rounds',
    'bet_round_scores'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = v_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', v_table);
    end if;
  end loop;
end;
$$;
